server {
    listen ${PORT};
    server_name localhost;

    # Directorio donde están los archivos del build de Angular
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Configuración para Angular Routing
    # Esto asegura que si el usuario recarga la página en una ruta (ej. /admin),
    # Nginx no de 404, sino que cargue el index.html y deje que Angular maneje la ruta.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché optimizada para archivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Manejo de errores
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
